### PR TITLE
Multiple ultrasonic support

### PR DESCRIPTION
**Pull request by frjalex**
A nested class is used to map to the 4 physical location on the DIO pins.

### CODE REVIEW

**Comment by frjalex** [comment]
I didn't use the enumarate way Connor suggested because it's a little complicated and a hardcoded version for use is enough.

**Comment by msbense** [comment]
BTW Alex you don't need to make an instance of Statics, ie:
`this.srFront = new SonicRangeSensor(Statics.FRONT_Ultra_Echo, Statics.FRONT_Ultra_Trigger);`
should be 
`this.srFront = new SonicRangeSensor(Statics.FRONT_Ultra_Echo, Statics.FRONT_Ultra_Trigger);`

**Comment by frjalex** [comment]
I couldn't difference (the two lines are the same)...

**Comment by frjalex** [comment]
Oh you're right! I'll correct this by adding a commit right now.
Thanks.

**Comment by frjalex** [comment]
So https://github.com/team5181/2016Robot/pull/56/commits/cc0b06388723206d44200cecc00c5d254b3338ff shall be what you're talking about. ;)

**Pull request merged**
